-- TCL (Transaction control language): to manage transactions done in the DB
-- 1.START TRANSACTION: begin a transaction
-- 2.COMMIT: apply all the changes and end transaction
-- 3.ROLLBACK: discard changes and end transactions
-- 4.SAVEPOINT: checkout within the group of transactions in which to rollback.