CREATE DATABASE AMAZON_CUSTOMER;

SHOW DATABASES;

USE AMAZON_CUSTOMER;

CREATE TABLE AMZ_CUSTOMER (
    AMZ_ID INT PRIMARY KEY,
    CUS_FIRST_NAME VARCHAR(255),
    CUS_LAST_NAME VARCHAR(255),
    CUS_CITY VARCHAR(255),
    CUS_NUMBER_OF_PRODUCT INT
);

INSERT INTO
    AMZ_CUSTOMER (
        AMZ_ID,
        CUS_FIRST_NAME,
        CUS_LAST_NAME,
        CUS_CITY,
        CUS_NUMBER_OF_PRODUCT
    )
VALUES (
        101,
        'KRUSHI',
        'MONPARA',
        'SURAT',
        21
    ),
    (
        102,
        'JAY',
        'VANPARIYA',
        'VAPI',
        24
    ),
    (
        103,
        'KISHAN',
        'AMBANI',
        'MORBI',
        45
    );

SELECT * FROM AMZ_CUSTOMER;

CREATE TABLE AMZ_CUSTOMER_BANK_DETAILS (
    BANK_NAME VARCHAR(255),
    PAN_NUMBER VARCHAR(255),
    AMZ_ID INT,
    FOREIGN KEY (AMZ_ID) REFERENCES AMZ_CUSTOMER (AMZ_ID) ON DELETE SET NULL
);

INSERT INTO
    AMZ_CUSTOMER_BANK_DETAILS (BANK_NAME, PAN_NUMBER, AMZ_ID)
VALUES ('SBI', 'IVOPM9021A', 101),
    ('BOB', 'IVOMP9078G', 102),
    ('HDFC', 'IBNK9045Y', 103);

SELECT * FROM AMZ_CUSTOMER_BANK_DETAILS;

DELETE FROM AMZ_CUSTOMER WHERE AMZ_ID = 101;

DROP DATABASE AMAZON_CUSTOMER;